author: "cagingulsen"
category: "admin"
summary: "Filters chat packets for latitude and longitude information"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:cagingulsen/customEjabberdModules.git"
